version: "3.9"
services:
  rust:
    build: scripts/edit_history/Dockerfile
    volumes:
      - .:/code
    environment:
      - ES_URL=elasticsearch
      - ES_USERNAME=elastic
      - ES_PASSWORD=$ELASTIC_PASSWORD
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  esdata:
    driver: local
