version: "3.3"
services:
  fetch_edit_history:
    build: scripts/edit_history
    volumes:
      - .:/code
    environment:
      - MONGO_URL=localhost:27017
      - MONGO_USERNAME=$MONGO_DB_USER
      - MONGO_PASSWORD=$MONGO_DB_PASS
    network_mode: "host"

  jupyter_notebook:
      build: notebooks
      user: root
      working_dir: /home/alejgh/work
      volumes:
        - ./notebooks:/home/alejgh/work
        - ./data:/home/alejgh/data
      environment:
        - NB_USER=alejgh
        - CHOWN_HOME=yes
        - RESTARTABLE=yes
        - MONGO_URL=mongo:27017
        - MONGO_USERNAME=$MONGO_DB_USER
        - MONGO_PASSWORD=$MONGO_DB_PASS
      ports:
        - 8888:8888
      command: "start-notebook.sh"
      network_mode: "host"

  mongo:
    image: mongo
    restart: always
    command:
        - '-f'
        - '/etc/mongod.conf'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASS
      - MONGO_INITDB_USERNAME=$MONGO_DB_USER
      - MONGO_INITDB_PASSWORD=$MONGO_DB_PASS
      - MONGO_INITDB_DATABASE=wd_diff
    volumes:
      - mongodata:/data/db
      - ./config/mongod.conf:/etc/mongod.conf
      - ./config/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    network_mode: "host"

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_EXPRESS_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_EXPRESS_PASS
      - ME_CONFIG_MONGODB_BASICAUTH_USERNAME=$MONGO_EXPRESS_USER
      - ME_CONFIG_MONGODB_BASICAUTH_PASSWORD=$MONGO_EXPRESS_PASS
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASS}@localhost:27017/
    ports:
      - 8081:8081
    depends_on:
      - "mongo"
    network_mode: "host"

volumes:
  mongodata:
